# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.7

ENV cluster.name=test-cluster-elasticsearch
ENV network.host=0.0.0.0
ENV transport.host=localhost
ENV xpack.security.enabled=false
ENV ES_JAVA_OPTS="-Xms2048m -Xmx2048m"